"""initial schema

Revision ID: c0cea8e3054d
Revises: 
Create Date: 2026-07-17 12:58:36.941795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0cea8e3054d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(length=100), nullable=False),
    sa.Column('requester_phone', sa.String(length=15), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('hospital', sa.String(length=150), nullable=True),
    sa.Column('blood_group_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('upazila_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_requests_id'), 'blood_requests', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('blood_group_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('upazila_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_blood_requests_id'), table_name='blood_requests')
    op.drop_table('blood_requests')
    # ### end Alembic commands ###
